// Lokasi: lib/features/guru_staff/widgets/import_staff_dialog.dart

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:file_picker/file_picker.dart';
import 'package:csv/csv.dart';
import '../models/penugasan_staf_model.dart';
import '../providers/staff_provider.dart'; // Sesuaikan path
import '../services/guru_dan_staff_bulk_service.dart';
import '../../../core/providers/app_context_provider.dart';

class ImportStaffDialog extends ConsumerStatefulWidget {
  const ImportStaffDialog({super.key});

  @override
  ConsumerState<ImportStaffDialog> createState() => _StaffDialogState();
}

class _StaffDialogState extends ConsumerState<ImportStaffDialog> {
  bool _isProcessing = false;
  PlatformFile? _pickedFile;
  List<PenugasanStafModel> _previewData = [];

  Future<void> _pickFile() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );

    if (result != null) {
      setState(() {
        _pickedFile = result.files.first;
        _previewData = [];
      });
      _parseCsv();
    }
  }

  Future<void> _parseCsv() async {
    if (_pickedFile == null || _pickedFile!.path == null) return;
    setState(() => _isProcessing = true);

    try {
      final appContext = ref.read(appContextProvider);
      final file = File(_pickedFile!.path!);
      final csvString = await file.readAsString();

      // FIX: Menggunakan CsvCodec agar sinkron dengan standar library 2026
      final fields = CsvCodec().decode(csvString);

      List<PenugasanStafModel> tempStaff = [];
      // Skip Header (i=1)
      for (var i = 1; i < fields.length; i++) {
        final row = fields[i];
        if (row.length >= 3) {
          tempStaff.add(
            PenugasanStafModel(
              id: '', // Generated by Auth
              lembagaId: appContext.lembaga?.id ?? '',
              // FIX: Sinkronisasi Lokasi (Pusat/Global/Cabang)
              cabangId: (row.length > 6 && row[6].toString().trim().isNotEmpty)
                  ? row[6].toString().trim()
                  : '', // Jika kosong/Pusat, kirim string kosong (akan di-null-kan di provider)
              profileId: '', // Generated by Auth
              namaStaf: row[0].toString(),
              nip: row[1].toString(),
              emailStaf: row[2].toString(),
              noHp: row[3].toString(),
              jenisKelamin: row[4].toString().toUpperCase() == 'L' ? 'L' : 'P',
              // FIX: Ambil Jabatan ID (Kolom 8)
              jabatanId: (row.length > 7 && row[7].toString().trim().isNotEmpty)
                  ? row[7].toString().trim()
                  : null,
              // FIX: Pastikan password tidak kosong (Signup requires a valid password)
              passwordSementara: (row.length > 8 && row[8].toString().trim().isNotEmpty)
                  ? row[8].toString()
                  : "User123!",
            ),
          );
        }
      }
      setState(() => _previewData = tempStaff);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Gagal membaca CSV: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      setState(() => _isProcessing = false);
    }
  }

  Future<void> _executeImport() async {
    if (_previewData.isEmpty) return;
    setState(() => _isProcessing = true);

    final success = await ref.read(staffListProvider.notifier).bulkImportStaff(_previewData);

    if (mounted) {
      setState(() => _isProcessing = false);
      if (success) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Berhasil mengimpor data Guru & Staff!'), backgroundColor: Color(0xFF10B981)),
        );
        Navigator.pop(context);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      title: const Text('Import Database Staff', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18)),
      content: SizedBox(
        width: double.maxFinite,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Kolom: Nama, NIP, Email, No HP, JK, Tgl Gabung, Lokasi, Jabatan, Password',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 11, color: Colors.grey),
            ),
            const SizedBox(height: 20),
            InkWell(
              onTap: _isProcessing ? null : _pickFile,
              borderRadius: BorderRadius.circular(16),
              child: Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: const Color(0xFFF1F5F9),
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: const Color(0xFFCBD5E1)),
                ),
                child: Column(
                  children: [
                    Icon(Icons.cloud_upload_outlined, size: 40, color: _pickedFile != null ? Colors.blue : Colors.grey),
                    const SizedBox(height: 12),
                    Text(_pickedFile?.name ?? 'Pilih File CSV Staff', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                  ],
                ),
              ),
            ),
            if (_previewData.isNotEmpty) ...[
              const SizedBox(height: 16),
              Text('Terdeteksi ${_previewData.length} calon staff siap impor.',
                  style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.blue)),
            ],
            if (_isProcessing) const Padding(padding: EdgeInsets.only(top: 16), child: LinearProgressIndicator()),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => ref.read(guruDanStaffBulkServiceProvider).unduhTemplateCsv(),
          child: const Text('Unduh Template', style: TextStyle(color: Colors.orange, fontWeight: FontWeight.bold)),
        ),
        TextButton(onPressed: () => Navigator.pop(context), child: const Text('Batal', style: TextStyle(color: Colors.grey))),
        ElevatedButton(
          onPressed: (_isProcessing || _previewData.isEmpty) ? null : _executeImport,
          style: ElevatedButton.styleFrom(backgroundColor: Colors.blue),
          child: const Text('PROSES IMPORT', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        ),
      ],
    );
  }
}